[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "graph-notebook"
description = "jupyter notebook extension to connect to graph databases"
readme = "README.md"
authors = [
    { name = "amazon-neptune", email = "amazon-neptune-pypi@amazon.com" },
]
keywords = [
    "gremlin",
    "jupyter",
    "neptune",
    "sparql",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.8",
]
dependencies = [
    "async-timeout>=4.0,<5.0",
    "boto3>=1.34.74",
    "botocore>=1.34.74",
    "gremlinpython>=3.5.1,<=3.7.2",
    "ipyfilechooser==0.6.0",
    "ipykernel==5.3.4",
    "ipython>=7.16.1,<=8.10.0",
    "ipywidgets==7.7.2",
    "itables>=2.0.0,<=2.1.0",
    "jedi>=0.18.1,<=0.18.2",
    "Jinja2>=3.0.3,<=3.1.4",
    "jupyter-contrib-nbextensions<=0.7.0",
    "jupyter==1.0.0",
    "jupyterlab_widgets>=1.0.0,<3.0.0",
    "nbclient<=0.7.3",
    "nbconvert>=6.3.0,<=7.2.8",
    "neo4j>=4.4.9,<5.0.0",
    "nest_asyncio>=1.5.5,<=1.5.6",
    "networkx==2.4",
    "notebook>=6.1.5,<7.0.0",
    "numpy<1.24.0",
    "pandas>=1.3.5,<=1.5.3",
    "rdflib==7.0.0",
    "requests>=2.32.0,<=2.32.2",
    "SPARQLWrapper==2.0.0",
    "widgetsnbextension<=3.6.1",
]
version = "4.5.0"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/aws/graph-notebook"

[tool.hatch.build.targets.sdist]
exclude = [
    ".github",
]

[tool.hatch.build.hooks.jupyter-builder]
dependencies = [
    "hatch-jupyter-builder>=0.9.1",
]
build-function = "hatch_jupyter_builder.npm_builder"

[tool.tbump]
field = [
    { name = "channel", default = "" },
    { name = "release", default = "" },
]

[tool.tbump.version]
current = "4.5.0"
regex = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)((?P<channel>a|b|rc|.dev)(?P<release>\\d+))?"

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "pyproject.toml"
version_template = "version = \"{major}.{minor}.{patch}{channel}{release}\""
