# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: amazon
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: graph_notebook_widgets
mimetype: ''
mimetype_name: ''
project_short_description: A Custom Jupyter Library for rendering NetworkX MultiDiGraphs
    using vis-network
python_name: graph_notebook_widgets
repository: <repository
test: false
viewer_name: ''

